## Importing the libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display all columns
pd.set_option('display.max_columns', None)

## Reading the dataset

In [4]:
# Load the dataset
df = pd.read_csv('data/new_retail_data.csv')
# Filter dataset for customers from Germany
df = df[df['Country'] == 'Germany']
# Display first few rows
df.head()

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,Age,Gender,Income,Customer_Segment,Date,Year,Month,Time,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
0,8691788.0,37249.0,Michelle Harrington,Ebony39@gmail.com,1.414787e+09,3959 Amanda Burgs,Dortmund,Berlin,77985.0,Germany,21.0,Male,Low,Regular,9/18/2023,2023.0,September,22:03:55,3.0,108.028757,324.086270,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.0,Cycling shorts
7,2344675.0,26603.0,Angela Fields,Tanya94@gmail.com,3.668096e+09,237 Young Curve,Munich,Berlin,86862.0,Germany,29.0,Male,Medium,Premium,3/24/2023,2023.0,March,10:12:56,1.0,46.588070,46.588070,Clothing,Zara,Shirt,Bad,Same-Day,Cash,Processing,1.0,Dress shirt
9,4926148.0,31878.0,Lori Bell,Jessica33@gmail.com,6.004895e+09,6225 William Lodge,Cologne,Berlin,64317.0,Germany,25.0,Male,Medium,New,10/4/2023,2023.0,October,22:27:40,10.0,397.611229,3976.112295,Home Decor,Home Depot,Decorations,Excellent,Standard,Cash,Delivered,4.0,Candles
17801,3680043.0,78484.0,Mr. Zachary Marks,Tyler6@gmail.com,2.831499e+09,085 Nguyen Highway,Cologne,Berlin,49173.0,Germany,19.0,Female,Medium,New,12/28/2023,2023.0,December,0:33:20,9.0,274.984254,2474.858288,Home Decor,Home Depot,Tools,Good,Express,PayPal,Delivered,4.0,Drill
17810,5206426.0,66989.0,Angel Fitzpatrick,Evan31@gmail.com,7.490023e+09,548 Gonzalez Camp,Leipzig,Berlin,95501.0,Germany,19.0,Male,Medium,New,6/6/2023,2023.0,June,17:41:53,2.0,85.717621,171.435242,Grocery,Coca-Cola,Water,Excellent,Standard,Debit Card,Delivered,5.0,Flavored water

## Data Cleaning

In [6]:
# Drop duplicates if any
df = df.drop_duplicates()

In [7]:
#Convert numeric columns to integer
cols = ['Transaction_ID','Customer_ID','Zipcode','Age','Year','Total_Purchases']
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')  
df[cols] = df[cols].fillna(0).astype(np.int64)

In [8]:
#Format Phone number to a standard form
df['Phone']=df['Phone'].apply(lambda x: str(x))
df['Phone']= df['Phone'].apply(lambda x: x[0:3]+'-'+x[3:6]+'-'+x[6:10])

In [9]:
# Convert date column to datetime
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

# Format the date as day-month-year
df['Date'] = df['Date'].dt.strftime('%d-%m-%Y')

In [10]:
# Convert time column to datetime
df['Time'] = pd.to_datetime(df['Time'], format='%H:%M', errors='coerce')

# Format time to show hours and minutes only
df['Time'] = df['Time'].dt.strftime('%H:%M')

In [11]:
# Convert columns to numeric, forcing non-convertible values to NaN
df['Age'] = df['Age'].replace('', pd.NA)
df['Total_Amount'] = df['Total_Amount'].replace('', pd.NA)
df['Total_Purchases'] = df['Total_Purchases'].replace('', pd.NA)

df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
df['Total_Amount'] = pd.to_numeric(df['Total_Amount'], errors='coerce')
df['Total_Purchases'] = pd.to_numeric(df['Total_Purchases'], errors='coerce')

In [12]:
# changing the float numbers to 2 decimal places
pd.set_option('display.float_format', lambda x: '%.2f' % x)
df.head()

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,Age,Gender,Income,Customer_Segment,Date,Year,Month,Time,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
0,8691788,37249,Michelle Harrington,Ebony39@gmail.com,141-478-6801,3959 Amanda Burgs,Dortmund,Berlin,77985,Germany,21,Male,Low,Regular,18-09-2023,2023,September,NaN,3,108.03,324.09,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.00,Cycling shorts
7,2344675,26603,Angela Fields,Tanya94@gmail.com,366-809-6144,237 Young Curve,Munich,Berlin,86862,Germany,29,Male,Medium,Premium,24-03-2023,2023,March,NaN,1,46.59,46.59,Clothing,Zara,Shirt,Bad,Same-Day,Cash,Processing,1.00,Dress shirt
9,4926148,31878,Lori Bell,Jessica33@gmail.com,600-489-5059,6225 William Lodge,Cologne,Berlin,64317,Germany,25,Male,Medium,New,04-10-2023,2023,October,NaN,10,397.61,3976.11,Home Decor,Home Depot,Decorations,Excellent,Standard,Cash,Delivered,4.00,Candles
17801,3680043,78484,Mr. Zachary Marks,Tyler6@gmail.com,283-149-9082,085 Nguyen Highway,Cologne,Berlin,49173,Germany,19,Female,Medium,New,28-12-2023,2023,December,NaN,9,274.98,2474.86,Home Decor,Home Depot,Tools,Good,Express,PayPal,Delivered,4.00,Drill
17810,5206426,66989,Angel Fitzpatrick,Evan31@gmail.com,749-002-3454,548 Gonzalez Camp,Leipzig,Berlin,95501,Germany,19,Male,Medium,New,06-06-2023,2023,June,NaN,2,85.72,171.44,Grocery,Coca-Cola,Water,Excellent,Standard,Debit Card,Delivered,5.00,Flavored water

In [13]:
# filling out missing values
df['Amount'] = df['Amount'].replace('',0)
df['Total_Amount'] = df['Total_Amount'].fillna(df['Total_Purchases']*df['Amount'])
df['Date'] = df['Date'].fillna('')
df['Time'] = df['Time'].fillna('')

## Fixing Wrong Data in State Column

In [15]:
# Dictionary mapping cities in Germany to their correct states
german_city_to_state = {
    "Berlin": "Berlin",
    "Hamburg": "Hamburg",
    "Munich": "Bavaria",
    "Cologne": "North Rhine-Westphalia",
    "Frankfurt": "Hesse",
    "Stuttgart": "Baden-Württemberg",
    "Düsseldorf": "North Rhine-Westphalia",
    "Dortmund": "North Rhine-Westphalia",
    "Essen": "North Rhine-Westphalia",
    "Leipzig": "Saxony",
    "Bremen": "Bremen",
    "Dresden": "Saxony",
    "Hanover": "Lower Saxony",
    "Nuremberg": "Bavaria",
    "Duisburg": "North Rhine-Westphalia",
    "Bochum": "North Rhine-Westphalia",
    "Wuppertal": "North Rhine-Westphalia",
    "Bielefeld": "North Rhine-Westphalia",
    "Bonn": "North Rhine-Westphalia",
    "Münster": "North Rhine-Westphalia",
    "Karlsruhe": "Baden-Württemberg",
    "Mannheim": "Baden-Württemberg",
    "Augsburg": "Bavaria",
    "Wiesbaden": "Hesse",
    "Gelsenkirchen": "North Rhine-Westphalia",
    "Mönchengladbach": "North Rhine-Westphalia",
    "Braunschweig": "Lower Saxony",
    "Kiel": "Schleswig-Holstein",
    "Aachen": "North Rhine-Westphalia",
    "Chemnitz": "Saxony",
    "Halle (Saale)": "Saxony-Anhalt",
    "Magdeburg": "Saxony-Anhalt",
    "Freiburg im Breisgau": "Baden-Württemberg",
    "Krefeld": "North Rhine-Westphalia",
    "Lübeck": "Schleswig-Holstein",
    "Oberhausen": "North Rhine-Westphalia",
    "Erfurt": "Thuringia",
    "Mainz": "Rhineland-Palatinate",
    "Rostock": "Mecklenburg-Western Pomerania",
    "Kassel": "Hesse",
    "Hagen": "North Rhine-Westphalia",
    "Hamm": "North Rhine-Westphalia",
    "Saarbrücken": "Saarland",
    "Mülheim an der Ruhr": "North Rhine-Westphalia",
    "Potsdam": "Brandenburg",
    "Ludwigshafen am Rhein": "Rhineland-Palatinate",
    "Oldenburg": "Lower Saxony",
    "Leverkusen": "North Rhine-Westphalia",
    "Osnabrück": "Lower Saxony",
    "Solingen": "North Rhine-Westphalia",
    "Heidelberg": "Baden-Württemberg",
    "Herne": "North Rhine-Westphalia",
    "Neuss": "North Rhine-Westphalia",
    "Darmstadt": "Hesse",
    "Paderborn": "North Rhine-Westphalia",
    "Regensburg": "Bavaria",
    "Ingolstadt": "Bavaria",
    "Würzburg": "Bavaria",
}

# Update the state column based on the city
df["State"] = df["City"].map(german_city_to_state).fillna(df["State"])

df.head()

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,Age,Gender,Income,Customer_Segment,Date,Year,Month,Time,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
0,8691788,37249,Michelle Harrington,Ebony39@gmail.com,141-478-6801,3959 Amanda Burgs,Dortmund,North Rhine-Westphalia,77985,Germany,21,Male,Low,Regular,18-09-2023,2023,September,,3,108.03,324.09,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.00,Cycling shorts
7,2344675,26603,Angela Fields,Tanya94@gmail.com,366-809-6144,237 Young Curve,Munich,Bavaria,86862,Germany,29,Male,Medium,Premium,24-03-2023,2023,March,,1,46.59,46.59,Clothing,Zara,Shirt,Bad,Same-Day,Cash,Processing,1.00,Dress shirt
9,4926148,31878,Lori Bell,Jessica33@gmail.com,600-489-5059,6225 William Lodge,Cologne,North Rhine-Westphalia,64317,Germany,25,Male,Medium,New,04-10-2023,2023,October,,10,397.61,3976.11,Home Decor,Home Depot,Decorations,Excellent,Standard,Cash,Delivered,4.00,Candles
17801,3680043,78484,Mr. Zachary Marks,Tyler6@gmail.com,283-149-9082,085 Nguyen Highway,Cologne,North Rhine-Westphalia,49173,Germany,19,Female,Medium,New,28-12-2023,2023,December,,9,274.98,2474.86,Home Decor,Home Depot,Tools,Good,Express,PayPal,Delivered,4.00,Drill
17810,5206426,66989,Angel Fitzpatrick,Evan31@gmail.com,749-002-3454,548 Gonzalez Camp,Leipzig,Saxony,95501,Germany,19,Male,Medium,New,06-06-2023,2023,June,,2,85.72,171.44,Grocery,Coca-Cola,Water,Excellent,Standard,Debit Card,Delivered,5.00,Flavored water

In [16]:
# Select only the necessary columns for this analysis
columns_to_keep = [
    "Product_Type", "Product_Category", "Total_Purchases", "Amount", 
    "Total_Amount", "Date", "Year", "Month", "City", "State", "Country", "Order_Status"
]
# Keep only the selected columns
df = df[columns_to_keep]
df.head()

,Product_Type,Product_Category,Total_Purchases,Amount,Total_Amount,Date,Year,Month,City,State,Country,Order_Status
0,Shorts,Clothing,3,108.03,324.09,18-09-2023,2023,September,Dortmund,North Rhine-Westphalia,Germany,Shipped
7,Shirt,Clothing,1,46.59,46.59,24-03-2023,2023,March,Munich,Bavaria,Germany,Processing
9,Decorations,Home Decor,10,397.61,3976.11,04-10-2023,2023,October,Cologne,North Rhine-Westphalia,Germany,Delivered
17801,Tools,Home Decor,9,274.98,2474.86,28-12-2023,2023,December,Cologne,North Rhine-Westphalia,Germany,Delivered
17810,Water,Grocery,2,85.72,171.44,06-06-2023,2023,June,Leipzig,Saxony,Germany,Delivered

## Managing the missing values

In [18]:
# Ensure Date column is in datetime format
df["Date"] = pd.to_datetime(df["Date"],dayfirst=True)

# Extract month from Date column
df["Extracted_Month"] = df["Date"].dt.month

# Replace missing values in Month column with extracted month
df["Month"] = df["Month"].fillna(df["Extracted_Month"])

# Drop the temporary Extracted_Month column 
df.drop(columns=["Extracted_Month"], inplace=True)

# Display updated DataFrame
df.head()

,Product_Type,Product_Category,Total_Purchases,Amount,Total_Amount,Date,Year,Month,City,State,Country,Order_Status
0,Shorts,Clothing,3,108.03,324.09,2023-09-18,2023,September,Dortmund,North Rhine-Westphalia,Germany,Shipped
7,Shirt,Clothing,1,46.59,46.59,2023-03-24,2023,March,Munich,Bavaria,Germany,Processing
9,Decorations,Home Decor,10,397.61,3976.11,2023-10-04,2023,October,Cologne,North Rhine-Westphalia,Germany,Delivered
17801,Tools,Home Decor,9,274.98,2474.86,2023-12-28,2023,December,Cologne,North Rhine-Westphalia,Germany,Delivered
17810,Water,Grocery,2,85.72,171.44,2023-06-06,2023,June,Leipzig,Saxony,Germany,Delivered

In [19]:
#find the columns with missing values
df.isnull().sum()

Product_Type         0
Product_Category    46
Total_Purchases      0
Amount              54
Total_Amount         0
Date                60
Year                 0
Month                0
City                31
State                0
Country              0
Order_Status        40
dtype: int64

In [20]:
# working on missing value in Amount column
null_rows = df[df["Amount"].isnull()]
print(null_rows)

                              Product_Type Product_Category  Total_Purchases  \
24618                                Water          Grocery                8
24962                           Literature            Books                5
26489                               Tablet      Electronics                1
27522                              T-shirt         Clothing                3
29802                               Snacks          Grocery                3
47688                           Smartphone      Electronics                5
52126                           Literature            Books                2
53188                              Kitchen       Home Decor                1
92966                                Water          Grocery                7
100028                             Kitchen       Home Decor                7
102103                         Non-Fiction            Books                8
102229                          Smartphone      Electronics                6
109134                               Tools       Home Decor                1
109475                              Coffee          Grocery                4
121764                              Shorts         Clothing                2
123995                          Smartphone      Electronics               10
131348                         Non-Fiction            Books                1
136735                              Fridge      Electronics                2
170479                            Bathroom       Home Decor                5
179837                             T-shirt         Clothing                7
180215                          Television      Electronics                1
181064                             Fiction            Books                3
181518                             T-shirt         Clothing                6
193356                             Bedding       Home Decor                9
199895                          Literature            Books                1
203463                             T-shirt         Clothing                7
203755                          Children's            Books                4
206354                               Shirt         Clothing                6
212301                              Tablet      Electronics                3
220034                             T-shirt         Clothing                2
222597                           Furniture       Home Decor                2
225958                          Soft Drink          Grocery                3
240445                         Non-Fiction            Books                2
243308                             Kitchen       Home Decor                8
250278                              Tablet      Electronics                2
256515                             Fiction            Books                3
257462                          Soft Drink          Grocery                1
257921                           Furniture       Home Decor                7
263925  Mitsubishi 1.5 Ton 3 Star Split AC      Electronics                5
264391  Mitsubishi 1.5 Ton 3 Star Split AC      Electronics               10
265369  Mitsubishi 1.5 Ton 3 Star Split AC      Electronics                5
269564  Mitsubishi 1.5 Ton 3 Star Split AC      Electronics                7
276317                             Bedding       Home Decor                2
280292                             Fiction            Books                2
280688                               Shirt         Clothing               10
282734                         Non-Fiction            Books                2
288578                              Laptop      Electronics                9
291055                               Juice          Grocery                3
292485                            Lighting       Home Decor               10
294074                              Snacks          Grocery               10
297425                         Decorations       Home Decor                3
298007                            Thriller            Books                9
299615                         Non-Fiction            Books                9
300706                           Furniture       Home Decor                5

        Amount  Total_Amount       Date  Year      Month        City  \
24618      NaN       1217.60 2023-09-09  2023  September   Frankfurt
24962      NaN        339.91 2023-10-04  2023    October   Frankfurt
26489      NaN        118.45 2023-11-20  2023   November   Frankfurt
27522      NaN        934.07 2023-10-17  2023    October   Frankfurt
29802      NaN        743.80 2023-11-06  2023   November   Frankfurt
47688      NaN       2074.61 2023-04-15  2023      April     Leipzig
52126      NaN        286.08 2023-06-16  2023       June    Duisburg
53188      NaN        159.63 2023-04-15  2023      April     Dresden
92966      NaN        276.36 2023-10-11  2023    October      Bochum
100028     NaN       1879.07 2023-10-21  2023    October      Bochum
102103     NaN       1612.55 2024-02-12  2024   February       Essen
102229     NaN       1346.84 2023-04-24  2023      April    Dortmund
109134     NaN        153.23 2023-06-15  2023       June     Dresden
109475     NaN       1559.95 2024-01-07  2024    January      Bremen
121764     NaN        641.22 2024-02-29  2024   February  Düsseldorf
123995     NaN       2701.48 2023-03-05  2023      March  Düsseldorf
131348     NaN        446.19 2024-01-17  2024    January     Hanover
136735     NaN        913.44 2023-06-30  2023    January      Berlin
170479     NaN       1641.87 2024-01-25  2024       July      Munich
179837     NaN        557.42 2023-04-21  2023      April   Bielefeld
180215     NaN        483.47 2023-10-15  2023    October  Düsseldorf
181064     NaN        566.05 2023-12-08  2023   December     Hamburg
181518     NaN        398.82 2023-06-12  2023       June      Munich
193356     NaN       3751.40 2023-12-05  2023   December   Stuttgart
199895     NaN        133.77 2024-01-21  2024    January        Bonn
203463     NaN       2783.60 2023-09-10  2023  September    Dortmund
203755     NaN        932.88 2023-08-20  2023     August   Wuppertal
206354     NaN       2181.43 2023-10-25  2023    October   Stuttgart
212301     NaN        140.24 2023-09-09  2023     August       Essen
220034     NaN        526.46 2024-02-14  2024     August      Munich
222597     NaN        313.04 2024-02-07  2024     August    Dortmund
225958     NaN       1145.03 2023-10-21  2023    October       Essen
240445     NaN        670.82 2023-07-23  2023        May     Dresden
243308     NaN       3533.49 2024-01-14  2024    January       Essen
250278     NaN        835.31 2023-10-04  2023    October      Bremen
256515     NaN        427.75 2023-08-14  2023     August     Dresden
257462     NaN        295.49 2023-10-01  2023    October    Duisburg
257921     NaN       2350.94 2023-10-18  2023    October      Munich
263925     NaN       2381.93 2023-07-17  2023      April      Bochum
264391     NaN       3533.40 2023-03-26  2023      April     Hamburg
265369     NaN       1052.35 2023-03-06  2023      April   Stuttgart
269564     NaN        244.23 2023-12-19  2023      April   Bielefeld
276317     NaN        638.63 2023-07-07  2023      April   Frankfurt
280292     NaN        432.26 2023-09-20  2023      April      Berlin
280688     NaN        339.56 2023-05-04  2023      April   Nuremberg
282734     NaN        151.75 2023-08-06  2023      April      Munich
288578     NaN       1863.76 2023-05-12  2023        May    Duisburg
291055     NaN        266.31 2023-03-28  2023      March     Dresden
292485     NaN       3153.96 2024-02-03  2024   February     Hamburg
294074     NaN        637.74 2023-09-21  2023  September     Münster
297425     NaN       1119.72 2023-03-28  2023      March   Stuttgart
298007     NaN       2199.40 2023-07-12  2023       July      Berlin
299615     NaN       4420.64 2023-11-22  2023   November     Münster
300706     NaN       1052.35 2023-03-06  2023      March   Stuttgart

                         State  Country Order_Status
24618                    Hesse  Germany    Delivered
24962                    Hesse  Germany    Delivered
26489                    Hesse  Germany    Delivered
27522                    Hesse  Germany    Delivered
29802                    Hesse  Germany    Delivered
47688                   Saxony  Germany    Delivered
52126   North Rhine-Westphalia  Germany   Processing
53188                   Saxony  Germany      Pending
92966   North Rhine-Westphalia  Germany      Shipped
100028  North Rhine-Westphalia  Germany      Shipped
102103  North Rhine-Westphalia  Germany      Shipped
102229  North Rhine-Westphalia  Germany      Shipped
109134                  Saxony  Germany   Processing
109475                  Bremen  Germany   Processing
121764  North Rhine-Westphalia  Germany    Delivered
123995  North Rhine-Westphalia  Germany    Delivered
131348            Lower Saxony  Germany    Delivered
136735                  Berlin  Germany    Delivered
170479                 Bavaria  Germany      Shipped
179837  North Rhine-Westphalia  Germany   Processing
180215  North Rhine-Westphalia  Germany    Delivered
181064                 Hamburg  Germany      Shipped
181518                 Bavaria  Germany   Processing
193356       Baden-Württemberg  Germany      Pending
199895  North Rhine-Westphalia  Germany    Delivered
203463  North Rhine-Westphalia  Germany      Pending
203755  North Rhine-Westphalia  Germany   Processing
206354       Baden-Württemberg  Germany      Shipped
212301  North Rhine-Westphalia  Germany    Delivered
220034                 Bavaria  Germany      Pending
222597  North Rhine-Westphalia  Germany   Processing
225958  North Rhine-Westphalia  Germany      Shipped
240445                  Saxony  Germany      Shipped
243308  North Rhine-Westphalia  Germany      Pending
250278                  Bremen  Germany      Shipped
256515                  Saxony  Germany      Shipped
257462  North Rhine-Westphalia  Germany    Delivered
257921                 Bavaria  Germany      Shipped
263925  North Rhine-Westphalia  Germany    Delivered
264391                 Hamburg  Germany    Delivered
265369       Baden-Württemberg  Germany    Delivered
269564  North Rhine-Westphalia  Germany    Delivered
276317                   Hesse  Germany      Pending
280292                  Berlin  Germany    Delivered
280688                 Bavaria  Germany   Processing
282734                 Bavaria  Germany   Processing
288578  North Rhine-Westphalia  Germany   Processing
291055                  Saxony  Germany    Delivered
292485                 Hamburg  Germany      Shipped
294074  North Rhine-Westphalia  Germany    Delivered
297425       Baden-Württemberg  Germany      Shipped
298007                  Berlin  Germany      Shipped
299615  North Rhine-Westphalia  Germany      Shipped
300706       Baden-Württemberg  Germany    Delivered

In [21]:
df['Amount'] = df['Amount'].fillna(df['Total_Amount']/df['Total_Purchases'])

In [22]:
# checking rows with null values
df.isnull().sum()

Product_Type         0
Product_Category    46
Total_Purchases      0
Amount               0
Total_Amount         0
Date                60
Year                 0
Month                0
City                31
State                0
Country              0
Order_Status        40
dtype: int64

In [23]:
#finding out null values in City column
null_rows = df[df["City"].isnull()]
print(null_rows)

       Product_Type Product_Category  Total_Purchases  Amount  Total_Amount  \
51312         Juice          Grocery                1  299.87        299.87
54838     Furniture       Home Decor                2  394.92        789.84
59735    Smartphone      Electronics                5  343.69       1718.46
64675    Television      Electronics                8  282.93       2263.46
67679    Headphones      Electronics                9  472.43       4251.88
94284         Water          Grocery                7   49.16        344.11
104593      Fiction            Books                4  370.00       1480.01
112642   Smartphone      Electronics                3  122.59        367.76
113914       Tablet      Electronics                5   16.94         84.70
119727        Water          Grocery                6  486.81       2920.88
127312      Bedding       Home Decor                9  291.73       2625.61
128459        Water          Grocery                3  182.22        546.66
133464   Children's            Books                3  320.86        962.57
135872       Fridge      Electronics                9  371.77       3345.92
139616       Fridge      Electronics                6   40.35        242.08
167229     Lighting       Home Decor                4   39.93        159.74
172376   Headphones      Electronics                1  344.84        344.84
176366  Non-Fiction            Books               10  208.11       2081.14
181605        Juice          Grocery                2   44.71         89.42
188473   Children's            Books                2  313.74        627.47
194918        Dress         Clothing                5  303.18       1515.92
196587     Bathroom       Home Decor                9  234.76       2112.88
202838   Headphones      Electronics                9  104.68        942.08
203152   Soft Drink          Grocery               10   18.68        186.78
212516   Smartphone      Electronics                1  131.25        131.25
235135      Fiction            Books                7  264.49       1851.42
240604       Tablet      Electronics                5   34.13        170.66
241375  Non-Fiction            Books                5  201.94       1009.71
261176      Fiction            Books                4   17.02         68.08
272614       Snacks          Grocery                2   63.65        127.30
288838       Snacks          Grocery                1  353.23        353.23

             Date  Year      Month City   State  Country Order_Status
51312  2023-06-06  2023       June  NaN  Berlin  Germany   Processing
54838  2023-08-02  2023     August  NaN  Berlin  Germany   Processing
59735  2024-02-26  2024   February  NaN  Berlin  Germany    Delivered
64675  2023-09-10  2023  September  NaN  Berlin  Germany      Pending
67679  2024-02-25  2024   February  NaN  Berlin  Germany      Shipped
94284  2024-02-27  2024   February  NaN  Berlin  Germany      Shipped
104593 2024-01-26  2024    January  NaN  Berlin  Germany      Shipped
112642 2023-06-06  2023       June  NaN  Berlin  Germany   Processing
113914 2023-05-08  2023        May  NaN  Berlin  Germany   Processing
119727 2023-03-09  2023      March  NaN  Berlin  Germany    Delivered
127312 2024-02-01  2024   February  NaN  Berlin  Germany    Delivered
128459 2023-03-06  2023      March  NaN  Berlin  Germany    Delivered
133464 2023-08-05  2023    January  NaN  Berlin  Germany    Delivered
135872 2023-08-28  2023    January  NaN  Berlin  Germany    Delivered
139616 2023-11-22  2023    January  NaN  Berlin  Germany    Delivered
167229 2023-08-24  2023     August  NaN  Berlin  Germany   Processing
172376 2023-07-20  2023       July  NaN  Berlin  Germany      Pending
176366 2023-11-29  2023       July  NaN  Berlin  Germany      Pending
181605 2023-10-19  2023    October  NaN  Berlin  Germany      Pending
188473 2023-05-13  2023        May  NaN  Berlin  Germany      Pending
194918 2023-05-13  2023        May  NaN  Berlin  Germany      Pending
196587 2023-07-25  2023       July  NaN  Berlin  Germany   Processing
202838 2024-02-20  2024   February  NaN  Berlin  Germany      Shipped
203152 2023-07-30  2023       July  NaN  Berlin  Germany   Processing
212516 2023-09-30  2023     August  NaN  Berlin  Germany      Pending
235135 2023-04-16  2023        May  NaN  Berlin  Germany      Shipped
240604 2023-11-20  2023        May  NaN  Berlin  Germany      Shipped
241375 2023-10-02  2023        May  NaN  Berlin  Germany   Processing
261176 2023-09-25  2023  September  NaN  Berlin  Germany   Processing
272614 2023-12-22  2023      April  NaN  Berlin  Germany    Delivered
288838 2023-08-20  2023     August  NaN  Berlin  Germany   Processing

In [24]:
# fixing missing values
df["City"] = df["City"].astype(str).replace("NaN", "Berlin")

In [25]:
# checking rows with null values
df.isnull().sum()

Product_Type         0
Product_Category    46
Total_Purchases      0
Amount               0
Total_Amount         0
Date                60
Year                 0
Month                0
City                 0
State                0
Country              0
Order_Status        40
dtype: int64

In [26]:
# checking Order Status NaN rows
null_rows = df[df["Order_Status"].isnull()]
print(null_rows)

       Product_Type Product_Category  Total_Purchases  Amount  Total_Amount  \
47749    Headphones      Electronics                1  478.91        478.91
52331    Television      Electronics                7   88.49        619.44
61632         Jeans         Clothing                7   89.69        627.81
66456       Kitchen       Home Decor                7  128.15        897.03
107192    Chocolate          Grocery                7   72.01        504.10
170848    Furniture       Home Decor                1  477.77        477.77
171622  Non-Fiction            Books                1  195.77        195.77
173920  Non-Fiction            Books                8  164.22       1313.77
174448       Jacket         Clothing                3  365.52       1096.55
178301        Water          Grocery                4  313.35       1253.41
184302        Dress         Clothing                8  217.45       1739.57
186496  Decorations       Home Decor                1  347.00        347.00
189925      Fiction            Books                1  180.31        180.31
204430       Snacks          Grocery               10  207.01       2070.05
204553   Television      Electronics                2  133.14        266.27
205805        Jeans         Clothing                8  179.68       1437.43
207244        Juice          Grocery                1  188.19        188.19
209703       Tablet      Electronics                2  216.39        432.77
212001    Furniture       Home Decor                8  491.47       3931.79
213007    Chocolate          Grocery                5   76.98        384.88
220204        Shoes         Clothing                9   30.18        271.65
222324        Shoes         Clothing                9   99.68        897.15
229789  Non-Fiction            Books                1  212.48        212.48
230665       Shorts         Clothing                5  374.19       1870.93
231123  Decorations       Home Decor                2  344.35        688.71
231663      Kitchen       Home Decor                9  378.53       3406.75
241673   Literature            Books                7  417.68       2923.79
245998      T-shirt         Clothing                3  461.65       1384.94
247956      Fiction            Books                1  125.34        125.34
249119  Non-Fiction            Books                9  497.89       4480.98
249732   Soft Drink          Grocery                8  408.62       3268.92
250168    Furniture       Home Decor                5  489.17       2445.87
250765        Shoes         Clothing                2  410.25        820.51
252896   Smartphone      Electronics                2  233.23        466.47
272998     Lighting       Home Decor                2  375.49        750.97
280381        Jeans         Clothing                7  323.95       2267.67
288648      Bedding       Home Decor               10  491.45       4914.48
296252       Laptop      Electronics                3  248.82        746.45
298352   Smartphone      Electronics                2  479.65        959.31
298664       Tablet      Electronics                7  225.32       1577.27

             Date  Year     Month        City                   State  \
47749  2023-05-22  2023       May   Stuttgart       Baden-Württemberg
52331  2023-11-09  2023  November    Dortmund  North Rhine-Westphalia
61632  2024-01-01  2024   January     Leipzig                  Saxony
66456  2024-01-20  2024   January     Cologne  North Rhine-Westphalia
107192 2023-04-25  2023     April   Wuppertal  North Rhine-Westphalia
170848 2023-11-08  2023      July   Wuppertal  North Rhine-Westphalia
171622 2023-10-16  2023      July      Bremen                  Bremen
173920 2023-03-23  2023      July    Duisburg  North Rhine-Westphalia
174448 2023-06-11  2023      July     Cologne  North Rhine-Westphalia
178301 2023-03-21  2023      July   Stuttgart       Baden-Württemberg
184302 2023-10-11  2023   October    Duisburg  North Rhine-Westphalia
186496 2023-11-04  2023  November      Bochum  North Rhine-Westphalia
189925        NaT  2023    August    Duisburg  North Rhine-Westphalia
204430 2023-12-23  2023  December        Bonn  North Rhine-Westphalia
204553 2023-07-08  2023      July     Leipzig                  Saxony
205805 2023-07-17  2023      July  Düsseldorf  North Rhine-Westphalia
207244 2023-12-19  2023  December   Nuremberg                 Bavaria
209703 2023-06-08  2023    August       Essen  North Rhine-Westphalia
212001 2023-03-12  2023    August     Cologne  North Rhine-Westphalia
213007 2024-01-03  2024    August      Bochum  North Rhine-Westphalia
220204 2023-03-07  2023    August   Bielefeld  North Rhine-Westphalia
222324 2023-10-22  2023    August     Münster  North Rhine-Westphalia
229789 2023-03-31  2023     March   Wuppertal  North Rhine-Westphalia
230665 2024-02-04  2024  February     Dresden                  Saxony
231123 2023-05-25  2023       May     Cologne  North Rhine-Westphalia
231663 2024-01-07  2024   January   Bielefeld  North Rhine-Westphalia
241673 2023-09-12  2023       May     Hanover            Lower Saxony
245998 2024-02-23  2024  February   Stuttgart       Baden-Württemberg
247956 2024-01-21  2024   January     Leipzig                  Saxony
249119 2023-10-30  2023   October   Nuremberg                 Bavaria
249732 2024-02-06  2024  February    Dortmund  North Rhine-Westphalia
250168 2023-10-31  2023   October  Düsseldorf  North Rhine-Westphalia
250765 2023-06-14  2023      June       Essen  North Rhine-Westphalia
252896 2023-10-04  2023   October     Leipzig                  Saxony
272998 2023-08-19  2023     April      Bremen                  Bremen
280381 2023-10-30  2023     April        Bonn  North Rhine-Westphalia
288648 2023-06-03  2023      June    Dortmund  North Rhine-Westphalia
296252 2023-11-21  2023  November   Stuttgart       Baden-Württemberg
298352 2024-01-20  2024   January     Leipzig                  Saxony
298664 2023-04-12  2023     April   Nuremberg                 Bavaria

        Country Order_Status
47749   Germany          NaN
52331   Germany          NaN
61632   Germany          NaN
66456   Germany          NaN
107192  Germany          NaN
170848  Germany          NaN
171622  Germany          NaN
173920  Germany          NaN
174448  Germany          NaN
178301  Germany          NaN
184302  Germany          NaN
186496  Germany          NaN
189925  Germany          NaN
204430  Germany          NaN
204553  Germany          NaN
205805  Germany          NaN
207244  Germany          NaN
209703  Germany          NaN
212001  Germany          NaN
213007  Germany          NaN
220204  Germany          NaN
222324  Germany          NaN
229789  Germany          NaN
230665  Germany          NaN
231123  Germany          NaN
231663  Germany          NaN
241673  Germany          NaN
245998  Germany          NaN
247956  Germany          NaN
249119  Germany          NaN
249732  Germany          NaN
250168  Germany          NaN
250765  Germany          NaN
252896  Germany          NaN
272998  Germany          NaN
280381  Germany          NaN
288648  Germany          NaN
296252  Germany          NaN
298352  Germany          NaN
298664  Germany          NaN

In [27]:
# deleting rows with missing order status, not considering cancelled orders
df.dropna(subset=["Order_Status"], inplace=True)

In [28]:
# checking rows with null values
df.isnull().sum()

Product_Type         0
Product_Category    46
Total_Purchases      0
Amount               0
Total_Amount         0
Date                59
Year                 0
Month                0
City                 0
State                0
Country              0
Order_Status         0
dtype: int64

In [53]:
null_rows = df[df["Date"].isnull()]
print(null_rows)

                              Product_Type Product_Category  Total_Purchases  \
24175                                Shoes         Clothing                8
24976                               Tablet      Electronics                6
25210                            Furniture       Home Decor                1
25737                               Snacks          Grocery               10
25849                                Water          Grocery                1
26099                           Smartphone      Electronics               10
26799                                Shoes         Clothing                2
27998                                Shirt         Clothing               10
28078                               Coffee          Grocery                6
28101                           Smartphone      Electronics                2
33740                           Headphones      Electronics                2
34811                              Fiction            Books                4
35869                            Furniture       Home Decor                8
37359                                Shirt         Clothing                6
41106                           Smartphone      Electronics                1
51363                           Smartphone      Electronics               10
55764                           Smartphone      Electronics               10
56177                              Fiction            Books               10
58309                           Smartphone      Electronics                1
65033                              Fiction            Books                6
103523                          Smartphone      Electronics                4
110119                             T-shirt         Clothing                5
110398                              Tablet      Electronics                1
110473                             Kitchen       Home Decor                5
110749                              Shorts         Clothing                3
122804                              Snacks          Grocery                7
123444                          Television      Electronics                1
137637                              Fridge      Electronics                2
138317                              Fridge      Electronics                1
139959                              Fridge      Electronics                7
168041                              Jacket         Clothing                4
168274                            Thriller            Books                1
169201                               Shirt         Clothing                6
173093                             Kitchen       Home Decor               10
174964                            Bathroom       Home Decor                8
186656                           Furniture       Home Decor                4
190696                          Soft Drink          Grocery                7
193048                           Furniture       Home Decor                4
201039                          Smartphone      Electronics                7
204403                              Tablet      Electronics                4
215530                               Juice          Grocery                6
218608                            Lighting       Home Decor                2
226469                             T-shirt         Clothing               10
229981                          Headphones      Electronics                7
237903                         Decorations       Home Decor                3
242029                            Thriller            Books                2
243128                              Laptop      Electronics                2
243586                               Tools       Home Decor                5
252166                             T-shirt         Clothing                1
254254                          Television      Electronics                9
259449                               Shoes         Clothing                7
269418  Mitsubishi 1.5 Ton 3 Star Split AC      Electronics                1
270295                         BlueStar AC      Electronics                3
272612                             T-shirt         Clothing                2
274593                               Jeans         Clothing                5
275163                           Furniture       Home Decor                2
282174                          Smartphone      Electronics                2
298792                         Decorations       Home Decor                8
300754                          Smartphone      Electronics                1

        Amount  Total_Amount Date  Year      Month        City  \
24175   443.87       3550.99  NaT  2023    October   Frankfurt
24976   121.08        726.47  NaT  2023       June   Frankfurt
25210   378.98        378.98  NaT  2023   November   Frankfurt
25737   129.97       1299.67  NaT  2023    October   Frankfurt
25849   281.83        281.83  NaT  2023   December   Frankfurt
26099   428.03       4280.29  NaT  2023      April   Frankfurt
26799   236.15        472.30  NaT  2023        May   Frankfurt
27998   362.56       3625.61  NaT  2023     August   Frankfurt
28078   403.00       2418.02  NaT  2024    January   Frankfurt
28101    95.91        191.82  NaT  2023    October   Frankfurt
33740   400.37        800.73  NaT  2023      March   Wuppertal
34811    45.62        182.46  NaT  2023  September        Bonn
35869    27.06        216.50  NaT  2023      March   Wuppertal
37359   213.31       1279.87  NaT  2023  September   Frankfurt
41106    44.21         44.21  NaT  2023      April     Hanover
51363    14.99        149.95  NaT  2023      March    Duisburg
55764   288.01       2880.14  NaT  2023    October      Munich
56177   131.44       1314.41  NaT  2023   December       Essen
58309   252.50        252.50  NaT  2023        May   Wuppertal
65033    78.30        469.78  NaT  2023   November     Leipzig
103523  445.94       1783.77  NaT  2023       July   Bielefeld
110119  384.95       1924.75  NaT  2024   February   Bielefeld
110398  286.10        286.10  NaT  2023  September   Nuremberg
110473  442.37       2211.86  NaT  2023      March     Cologne
110749  289.58        868.75  NaT  2024   February      Bochum
122804  178.23       1247.59  NaT  2023      April     Münster
123444  495.46        495.46  NaT  2023      March   Nuremberg
137637  225.23        450.46  NaT  2023    January     Hanover
138317   86.25         86.25  NaT  2023    January     Dresden
139959  139.41        975.88  NaT  2023    January   Wuppertal
168041  383.68       1534.72  NaT  2023       July   Nuremberg
168274  233.79        233.79  NaT  2023       July       Essen
169201   48.99        293.95  NaT  2023       July   Frankfurt
173093   58.03        580.35  NaT  2023       July     Cologne
174964  231.53       1852.24  NaT  2023       July     Leipzig
186656  482.97       1931.88  NaT  2023      March      Munich
190696  248.21       1737.50  NaT  2024    January      Bochum
193048  167.13        668.50  NaT  2023   November   Stuttgart
201039  174.83       1223.80  NaT  2024   February   Stuttgart
204403  245.59        982.37  NaT  2023     August       Essen
215530   18.50        110.97  NaT  2023     August   Wuppertal
218608  358.83        717.66  NaT  2024     August   Stuttgart
226469   66.79        667.92  NaT  2023     August     Hamburg
229981  110.18        771.29  NaT  2023      March   Nuremberg
237903  106.64        319.92  NaT  2023        May   Bielefeld
242029  134.73        269.47  NaT  2023        May      Bochum
243128  292.22        584.45  NaT  2023        May    Dortmund
243586   65.81        329.03  NaT  2023  September  Düsseldorf
252166  234.48        234.48  NaT  2023      April       Essen
254254  475.36       4278.23  NaT  2023     August     Cologne
259449  266.77       1867.36  NaT  2023   November        Bonn
269418  157.35        157.35  NaT  2023      April   Stuttgart
270295  349.70       1049.10  NaT  2023      April     Leipzig
272612  325.01        650.02  NaT  2023      April   Nuremberg
274593  379.31       1896.54  NaT  2023      April   Wuppertal
275163   75.14        150.28  NaT  2023      April      Munich
282174  183.58        367.15  NaT  2024      April   Nuremberg
298792  213.32       1706.54  NaT  2023      April       Essen
300754  157.35        157.35  NaT  2023     August   Stuttgart

                         State  Country Order_Status
24175                    Hesse  Germany    Delivered
24976                    Hesse  Germany    Delivered
25210                    Hesse  Germany    Delivered
25737                    Hesse  Germany    Delivered
25849                    Hesse  Germany    Delivered
26099                    Hesse  Germany    Delivered
26799                    Hesse  Germany    Delivered
27998                    Hesse  Germany    Delivered
28078                    Hesse  Germany    Delivered
28101                    Hesse  Germany    Delivered
33740   North Rhine-Westphalia  Germany    Delivered
34811   North Rhine-Westphalia  Germany    Delivered
35869   North Rhine-Westphalia  Germany    Delivered
37359                    Hesse  Germany    Delivered
41106             Lower Saxony  Germany    Delivered
51363   North Rhine-Westphalia  Germany   Processing
55764                  Bavaria  Germany   Processing
56177   North Rhine-Westphalia  Germany   Processing
58309   North Rhine-Westphalia  Germany      Shipped
65033                   Saxony  Germany    Delivered
103523  North Rhine-Westphalia  Germany      Shipped
110119  North Rhine-Westphalia  Germany   Processing
110398                 Bavaria  Germany   Processing
110473  North Rhine-Westphalia  Germany   Processing
110749  North Rhine-Westphalia  Germany   Processing
122804  North Rhine-Westphalia  Germany    Delivered
123444                 Bavaria  Germany    Delivered
137637            Lower Saxony  Germany    Delivered
138317                  Saxony  Germany    Delivered
139959  North Rhine-Westphalia  Germany    Delivered
168041                 Bavaria  Germany      Pending
168274  North Rhine-Westphalia  Germany      Shipped
169201                   Hesse  Germany      Shipped
173093  North Rhine-Westphalia  Germany   Processing
174964                  Saxony  Germany      Pending
186656                 Bavaria  Germany    Delivered
190696  North Rhine-Westphalia  Germany    Delivered
193048       Baden-Württemberg  Germany      Shipped
201039       Baden-Württemberg  Germany   Processing
204403  North Rhine-Westphalia  Germany      Pending
215530  North Rhine-Westphalia  Germany      Pending
218608       Baden-Württemberg  Germany   Processing
226469                 Hamburg  Germany   Processing
229981                 Bavaria  Germany    Delivered
237903  North Rhine-Westphalia  Germany      Shipped
242029  North Rhine-Westphalia  Germany   Processing
243128  North Rhine-Westphalia  Germany      Pending
243586  North Rhine-Westphalia  Germany   Processing
252166  North Rhine-Westphalia  Germany      Pending
254254  North Rhine-Westphalia  Germany      Shipped
259449  North Rhine-Westphalia  Germany    Delivered
269418       Baden-Württemberg  Germany    Delivered
270295                  Saxony  Germany    Delivered
272612                 Bavaria  Germany      Shipped
274593  North Rhine-Westphalia  Germany    Delivered
275163                 Bavaria  Germany      Shipped
282174                 Bavaria  Germany      Shipped
298792  North Rhine-Westphalia  Germany      Shipped
300754       Baden-Württemberg  Germany    Delivered

In [55]:
# Function to generate a random date
def random_date(year, month):
    try:
        # Get the number of days in the given month and year
        days_in_month = pd.Period(f"{year}-{month}").days_in_month
        # Generate a random day
        day = np.random.randint(1, days_in_month + 1)
        return pd.to_datetime(f"{year}-{month}-{day}")
    except:
        return pd.NaT  # Return NaT if the date cannot be created

# Ensure 'Date' column is in datetime format
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

# Apply function only where 'Date' is missing
df.loc[df['Date'].isna(), 'Date'] = df.apply(
    lambda row: random_date(row['Year'], row['Month']) if pd.isna(row['Date']) else row['Date'], axis=1
)

In [59]:
# checking rows with null values
df.isnull().sum()

Product_Type         0
Product_Category    46
Total_Purchases      0
Amount               0
Total_Amount         0
Date                 0
Year                 0
Month                0
City                 0
State                0
Country              0
Order_Status         0
dtype: int64

In [65]:
# filling missing product categories
df['Product_Category'] = df.groupby('Product_Type')['Product_Category'].transform(lambda x: x.ffill().bfill())

In [67]:
# checking rows with null values
df.isnull().sum()

Product_Type        0
Product_Category    0
Total_Purchases     0
Amount              0
Total_Amount        0
Date                0
Year                0
Month               0
City                0
State               0
Country             0
Order_Status        0
dtype: int64